const frontRoutes = {
  cookies: '/cookies',
  diet: '/diet',
  dietsConfig: '/config/diets',
  home: '/home',
  login: '/login',
  main: '/main',
  marathonList: '/marathons',
  meditation: '/meditation',
  meditationsConfig: '/config/meditations',
  planning: '/config/planning',
  privacyPolicy: '/privacy-policy',
  progress: '/progress',
  recipeDetails: '/recipe/:id',
  register: '/register',
  tasksConfig: '/config/tasks',
  terms: '/terms-and-conditions',
  todoList: '/todolist',
  users: '/users',
  workoutDetails: '/config/workout/:id',
  workouts: '/workouts',
  workoutsConfig: '/config/workouts',
};

export default frontRoutes;
